# http://www.appveyor.com/docs/appveyor-yml
image: Visual Studio 2019

version: "{build}"

environment:
  nodejs_version: "14"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install --loglevel=warn

test_script:
  - yarn run test

# Disable automatic builds
build: off
